export const ADD_EMPLOYEE_ERROR = 'ADD_EMPLOYEE_ERROR';
export const ADD_EMPLOYEE_LOADING = 'ADD_EMPLOYEE_LOADING';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';

export const DELETE_EMPLOYEE_ERROR = 'DELETE_EMPLOYEE_ERROR';
export const DELETE_EMPLOYEE_LOADING = 'DELETE_EMPLOYEE_LOADING';
export const DELETE_EMPLOYEE_BOOK_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';

export const EDIT_EMPLOYEE_ERROR = 'EDIT_EMPLOYEE_ERROR';
export const EDIT_EMPLOYEE_LOADING = 'EDIT_EMPLOYEE_LOADING';
export const EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS';

export const FETCH_EMPLOYEES_ERROR = 'FETCH_EMPLOYEES_ERROR';
export const FETCH_EMPLOYEES_LOADING = 'FETCH_EMPLOYEES_LOADING';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
